import { useState } from 'react';
import { motion } from 'framer-motion';
import { AlertTriangle, Loader2 } from 'lucide-react';
import { getAuthHeaders } from '../../utils/getAuthToken';
import { API_BASE_URL } from '../../config/api';

interface AutoPostDisclaimerProps {
  channelId: string;
  onAccepted: () => void;
  onCancel: () => void;
}

const DISCLAIMER_TEXT = `SocialFlow generates video content using artificial intelligence. We cannot guarantee the accuracy, appropriateness, completeness, or legality of AI-generated content. By enabling auto-post, you accept full and sole responsibility for all content published to your social media channel(s). SocialFlow, its affiliates, and its employees are not liable for any claims, damages, losses, or actions arising from content auto-posted on your behalf. You may disable auto-post at any time from your channel settings.`;

export default function AutoPostDisclaimer({ channelId, onAccepted, onCancel }: AutoPostDisclaimerProps) {
  const [checked, setChecked] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  const handleAccept = async () => {
    if (!checked) return;
    setSaving(true);
    try {
      const headers = await getAuthHeaders();
      const res = await fetch(`${API_BASE_URL}/channels/${channelId}/accept-disclaimer`, {
        method: 'POST',
        headers,
      });
      if (!res.ok) throw new Error('Failed to accept disclaimer');
      onAccepted();
    } catch (e) {
      setError('Could not save — please try again.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div role="dialog" aria-modal="true" className="fixed inset-0 bg-black/70 backdrop-blur-sm z-[60] flex items-center justify-center p-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.96 }}
        animate={{ opacity: 1, scale: 1 }}
        className="bg-[#0d1117] border border-amber-500/30 rounded-2xl p-6 w-full max-w-md"
      >
        <div className="flex items-center gap-3 mb-4">
          <AlertTriangle className="h-5 w-5 text-amber-400 shrink-0" />
          <h3 className="text-base font-semibold text-white">Auto-Post Requires Your Permission</h3>
        </div>
        <p className="text-sm text-white/50 leading-relaxed mb-4">
          By enabling auto-post, videos generated by AI will be published to your channel automatically without manual review.
        </p>
        <div className="bg-black/30 border border-amber-500/15 rounded-xl p-4 text-xs text-white/40 leading-relaxed mb-5">
          <strong className="text-amber-400">Disclaimer: </strong>{DISCLAIMER_TEXT}
        </div>
        <label className="flex items-start gap-3 cursor-pointer mb-5">
          <input
            type="checkbox"
            checked={checked}
            onChange={e => setChecked(e.target.checked)}
            className="mt-0.5 h-4 w-4 rounded border-white/20 bg-white/[0.02] text-teal-500 focus:ring-teal-500/50"
          />
          <span className="text-sm text-white/60">
            I understand that AI-generated content may be inaccurate and I accept full responsibility for all posts made to my channel.
          </span>
        </label>
        {error && <p className="text-red-400 text-xs mb-3">{error}</p>}
        <div className="flex gap-3">
          <button onClick={onCancel}
            className="flex-1 py-2.5 rounded-xl border border-white/[0.07] text-sm text-white/50 hover:text-white/80 hover:border-white/[0.14] transition-all">
            Cancel
          </button>
          <button
            disabled={!checked || saving}
            onClick={handleAccept}
            className="flex-1 flex items-center justify-center gap-2 py-2.5 rounded-xl bg-gradient-to-r from-teal-500 to-teal-400 text-sm font-medium text-black disabled:opacity-40 transition-opacity">
            {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
            Enable Auto-Post
          </button>
        </div>
      </motion.div>
    </div>
  );
}
